### ISSUE TITLE
Force positive K values

### ISSUE THREAD

**Issue by zhexingli** [adrn/thejoker#113]
Hello,

Is there a way to force the K returned by rejection sampling to be > 0? My rejection sampling somehow is allowing negative K values to pass through (see the corner plot). I double checked with `joker_samples['K'].value` and there are indeed negative Ks in the posterior.

![jokercorner](https://user-images.githubusercontent.com/18060088/120709245-73517980-c471-11eb-89ce-e031fed05b4f.png)

Thanks

**Comment by adrn** [comment]
Sure! With the samples that are returned, you can call, e.g., `samples.wrap_K()` and this adjusts the K and omega values appropriately.

**Comment by zhexingli** [comment]
Is this modifying the K samples in the posterior? Is there a way to force this say in the prior or before initializing the rejection sampling?

**Comment by adrn** [comment]
That modifies the posterior samples, yes. Out of curiosity, why do you want to change the prior?

**Comment by zhexingli** [comment]
I was thinking if I can enforce positive K in the prior then maybe the rejection sampling process can ignore all the negative ones and instead focus on the distribution in the constrained space and maybe making the process more efficient?

**Comment by adrn** [comment]
Negative K is equivalent to positive K, with omega rotated by 180 degrees. The prior is allowed to go negative because the prior has to be Gaussian (formally, for the marginalization over linear parameters to work). It won't improve the efficiency to restrict to positive K, so I think you are best off to just use `.wrap_K()` on the posterior samples after you run the sampler.

**Comment by zhexingli** [comment]
Ok I see. Thanks.

**Comment by zhexingli** [comment]
I'm having trouble understanding the effect of sigma_K0 on my priors. Just want to make sure here... Based on the equations for the priors, it appears that the semi-amplitude standard deviation becomes smaller with larger period because of the (P/P0)^(-1/3) term? Is there any recommendation on what value I should set for sigma_K0? Obviously I don't want the priors to be sampled within a very confined parameter space. Is there anyway to make the sigma the same for all tested period values?

**Comment by adrn** [comment]
>  it appears that the semi-amplitude standard deviation becomes smaller with larger period

That's right: The reasoning (as mentioned in the paper) is so that the prior is constant over companion mass at any period. Because mass ratio is related to semi-amplitude, if you use a constant sigma_K, you effectively allow a large range of companion masses at long periods and a small range of masses at short periods. You can certainly fix the K prior if you want (see the documentation for an example: https://thejoker.readthedocs.io/en/latest/examples/2-Customize-prior.html), but this can lead to some non-intuitive behavior if your data allow a large range of period values for the generated samples.

> Obviously I don't want the priors to be sampled within a very confined parameter space.

See comments above: This is a feature, not a bug. The prior is more confined in semi-amplitude but is constant in companion mass with P. If you make the prior constant in semi-amplitude, the prior will allow different companion masses at different periods.

**Comment by zhexingli** [comment]
Thank you. I guess the purpose of setting P0 with a different value is just to change the size of standard deviation at a particular period, but doesn't change the relative sigma between small and large period values right? Is having different P0 gonna significantly change the sample result?

**Comment by adrn** [comment]
Right - the `P0` parameter just sets a scale unit for the period. It is the period value at which the prior has variance equal to \sigma_{K,0}^2.

**Comment by zhexingli** [comment]
Thanks!
